pipeline {
    agent any
    
    environment {
        AWS_ACCESS_KEY_ID     = credentials('AWS_ACCESS_KEY')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_KEY')
        ANSIBLE_HOST_KEY_CHECKING = 'False'
    }
    
    stages {
        stage('Deploy Infrastructure') {
            steps {
                sh 'terraform init'
                sh 'terraform apply -auto-approve'
                
                // بنحفظ الـ Bastion IP في متغير عشان نستخدمه تحت
                script {
                    env.BASTION_IP = sh(script: "terraform output -raw bastion_public_ip", returnStdout: true).trim()
                    env.APP_IP = sh(script: "terraform output -raw app_private_ip", returnStdout: true).trim()
                }

                sh '''
                    echo "[bastion_host]" > ansible/inventory/hosts.ini
                    echo "${BASTION_IP}" >> ansible/inventory/hosts.ini
                    echo "\n[app_server]" >> ansible/inventory/hosts.ini
                    echo "${APP_IP}" >> ansible/inventory/hosts.ini
                '''
            }
        }
        
        stage('Configure Servers') {
            steps {
                dir('ansible') {
                    // شلنا القوس الزيادة واستخدمنا متغير الـ BASTION_IP
                    ansiblePlaybook(
                        playbook: 'playbooks/install_docker.yml',
                        inventory: 'inventory/hosts.ini',
                        credentialsId: 'aws-ssh-key',
                        installation: 'ansible',
                        disableHostKeyChecking: true,
                        extraVars: [
                            ansible_ssh_common_args: "-o ProxyCommand='ssh -W %h:%p -q ubuntu@${env.BASTION_IP} -i my-terraform-key -o StrictHostKeyChecking=no'"
                        ]
                    )
                }
            }
        }
    }
}