pipeline {
    agent any
    
    environment {
        AWS_ACCESS_KEY_ID     = credentials('AWS_ACCESS_KEY')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_KEY')
        // تعطيل التحقق من الـ Host Key عشان Ansible م يقفش يسأل Yes/No
        ANSIBLE_HOST_KEY_CHECKING = 'False'
    }
    
    stages {
        stage('Deploy Infrastructure') {
            steps {
                sh 'terraform init'
                sh 'terraform apply -auto-approve'
                
                // خطوة جوهرية: تحديث ملف الـ Inventory بالـ IPs الجديدة اللي تيرارفورم طلعها
                sh '''
                    echo "[bastion_host]" > ansible/inventory/hosts.ini
                    terraform output -raw bastion_public_ip >> ansible/inventory/hosts.ini
                    echo "\n[app_server]" >> ansible/inventory/hosts.ini
                    terraform output -raw app_private_ip >> ansible/inventory/hosts.ini
                '''
            }
        }
        
        stage('Configure Servers') {
            steps {
                dir('ansible') {
                    ansiblePlaybook(
                        playbook: 'playbooks/install_docker.yml',
                        inventory: 'inventory/hosts.ini',
                        credentialsId: 'aws-ssh-key',
                        installation: 'ansible',
                        // إضافة اختيار تجاهل الـ Host Key Checking لزيادة التأكيد
                        disableHostKeyChecking: true
                    )
                }
            }
        }
    }
}